# Restreint l'accès au buffer dmesg
kernel.dmesg_restrict=1

# Cache les addresses kernel dans /proc et les différentes autres interfaces
kernel.kptr_restrict=2

# Spécifie explicitement le nb d'id de process supportés
kernel.pid_max=32768

# Restreint l'utilisation du sous-système perf
kernel.perf_cpu_time_max_percent=1
kernel.perf_event_max_sample_rate=1

# Interdit l'accès non privilégié à l'appel système perf_event_open()
kernel.perf_event_paranoid=2

# Active l'ASLR
kernel.randomize_va_space=2

# Désactive les combinaisons des Magic System Request Key
kernel.sysrq=0

# Restreint l'usage du BPF noyau aux utilisateurs privilégiés
kernel.unprivileged_bpf_disabled=1

# Arrête complètement le système en cas de comportement inattendu du noyau Linux
kernel.panic_on_oops=1

# Atténuation de l'effet de dispersion du JIT noyau au coût d'un compromis sur
# les performances associées.
net.core.bpf_jit_harden=2

# Pour un serveur qui n'a pas besoin de faire du routage
net.ipv4.ip_forward=0
net.ipv4.conf.all.accept_local=0
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.all.secure_redirects=0
net.ipv4.conf.default.secure_redirects=0
net.ipv4.conf.all.shared_media=0
net.ipv4.conf.default.shared_media=0
net.ipv4.conf.all.accept_source_route=0
net.ipv4.conf.default.accept_source_route=0
# Empêche le noyau Linux de gérer la table ARP global
net.ipv4.conf.all.arp_filter=1
# Eviter du traffic arp bizarre hors lan
net.ipv4.conf.all.arp_ignore=2
# pr éviter arp poisoning
net.ipv4.conf.all.drop_gratuitous_arp=1
# Ignorer les réponses non conformes à la RFC 1122
net.ipv4.icmp_ignore_bogus_error_responses=1
# RFC 1337
net.ipv4.tcp_rfc1337=1
# Eviter attaque type SYN flood.
net.ipv4.tcp_syncookies=1

# Pas besoin d'ipv6 si notre serveu est full setup ipv4, mais a remove dans le cas ou on introduit del'ipv6
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6=1

# Restreint la création de liens symboliques à des fichiers dont l'utilisateur est propriétaire
fs.protected_symlinks=1
# Restreint la création de liens durs à des fichiers dont l'utilisateur est propriétaire
fs.protected_hardinks=1

